version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.4
    - 5.2.0
    - 5.2.1
    - 5.2.3
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.3
    - 5.2.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 2.34.0
  commit-message:
    prefix: chore
    include: scope
